spring:
  profiles:
    include: mapper
  application:
    name: market-common
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
          ssl:
            protocols: TLSv1.2

security:
  jwt:
    secret-key: testtesttesttesttesttesttesttesttesttesttest
    expire-length: 360000000