spring:
  application:
    name: market
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/market
    username: root
    password: 1027
  sql:
    init:
      mode: always
      continue-on-error: true
      schema-locations: classpath:sql/schema.sql
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
          ssl:
            protocols: TLSv1.2
  profiles:
    include: env

mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml

security:
  jwt:
    secret-key: testtesttesttesttesttesttesttesttesttesttest
    expire-length: 360000
