spring:
  profiles:
    active: default
    include: common
  application:
    name: market-socket

server:
  port: 8081

#logging:
#  level:
#    org.springframework.web.socket: TRACE
#    org.springframework.web.socket.server: TRACE
#    org.springframework.web.socket.sockjs: TRACE